### ISSUE TITLE
Feature Request - Add Create/Edit Alias links in Compact mode 

### ISSUE THREAD

**Issue by agillam69** [bullseye555/pagermon_utilities#3]
Can you add the ability to create new aliases for unknown capcodes when using compact mode on a mobile device (iPhone etc)?

**Comment by bullseye555** [comment]
Certainly doable @agillam69 

I'll work on it over the next week or two

**Comment by agillam69** [comment]
Sounds great

**Comment by bullseye555** [comment]
Sorry for the delay on this @agillam69 ! 

I've now done this - it's in the updates to PagerMon_Themes https://github.com/bullseye555/pagermon_themes I pushed out yesterday
